name: Notify Slack on Push

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,message,commit,author,ref
          custom_payload: |
            {
              "text": "🚀 Push to *${{ github.ref_name }}* by *${{ github.actor }}* in `${{ github.repository }}`"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
