name: Notify Slack on Push

on: [push]

jobs:
  slack-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": "Push to branch `${{ github.ref_name }}` by `${{ github.actor }}` in repo `${{ github.repository }}`"
            }
